version: '3.9'

services:

  database:
    container_name: node-postgress
    image: postgres
    environment:
      POSTGRES_PASSWORD: Pa55word@
      POSTGRES_USER: postgres 
      POSTGRES_DB: DEFAULT
    
    restart: always
    ports:
      - 5432:5432
    volumes:
      - node-postgres:/var/lib/postgressql/data
    networks:
      - node-network


volumes:
   node-postgres:
      external: true

networks:
   node-network:
      name: node-network  